annotations:
  fips: "true"
  images: |
    - name: os-shell
      version: "5"
      image: registry-1.docker.io/bitnami/os-shell:latest
    - name: postgres-exporter
      version: 0.18.1
      image: registry-1.docker.io/bitnami/postgres-exporter:latest
    - name: postgresql
      version: 18.1.0
      image: registry-1.docker.io/bitnami/postgresql:latest
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 18.1.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.33.2
description: "PostgreSQL (Postgres) is an open source object-relational database known for reliability and data integrity. ACID-compliant, it supports foreign keys, joins, views, triggers and stored procedures."
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
keywords:
- postgresql
- postgres
- database
- sql
- replication
- cluster
maintainers:
- name: "Broadcom, Inc. All Rights Reserved."
  url: https://github.com/bitnami/charts
name: postgresql
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/postgresql
version: 18.1.15
